- name: Install PostgreSQL on Debian-based systems
  ansible.builtin.apt:
    name: "{{ postgresql_packages_debian }}"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Install PostgreSQL on Red Hat-based systems
  ansible.builtin.yum:
    name: "{{ postgresql_packages_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Stop PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
  become: true

- name: Disable PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    enabled: no
  become: true

- name: Install Patroni dependencies on Debian-based systems
  ansible.builtin.apt:
    name: "{{ patroni_dependencies_debian }}"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Install Patroni dependencies on Red Hat-based systems
  ansible.builtin.yum:
    name: "{{ patroni_dependencies_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Upgrade pip and install Patroni
  ansible.builtin.shell: |
    pip3 install --upgrade pip
    pip3 install patroni python-etcd psycopg2
  become: true

- name: Create Patroni configuration file
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
  become: true

- name: Create Patroni systemd service file
  ansible.builtin.template:
    src: patroni.service.j2
    dest: /usr/lib/systemd/system/patroni.service
    mode: '0644'
  become: true

- name: Allow ports 5432 and 8008 through the firewall on Debian-based systems
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
  - 5432
  - 8008
  when: ansible_os_family == "Debian"
  become: true

- name: Allow ports 5432 and 8008 through the firewall on Red Hat-based systems
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
  - postgresql
  - http
  when: ansible_os_family == "RedHat"
  become: true

- name: Enable Patroni service
  ansible.builtin.systemd:
    name: patroni.service
    enabled: true
  become: true

- name: Start Patroni service
  ansible.builtin.systemd:
    name: patroni.service
    state: started
  become: true

- name: Check Patroni service logs
  ansible.builtin.shell: journalctl -u patroni.service -f
  become: true
  async: 60
  poll: 0

- name: Get Patroni cluster members
  ansible.builtin.shell: sudo -u postgres patronictl -c /etc/patroni.yml list
  become: true

- name: Detect the Patroni master node
  ansible.builtin.shell: |
    sudo -u postgres patronictl -c /etc/patroni.yml list | grep -w "Master"
  register: patroni_master_check
  become: true

- name: Set fact if this is the master node
  ansible.builtin.set_fact:
    is_patroni_master: "{{ 'Master' in patroni_master_check.stdout }}"

- name: Create test table on master
  ansible.builtin.shell: |
    psql -U postgres -c "create table mydata(key text, value text);"
    psql -U postgres -c "insert into mydata values('foo', 'bar');"
  when: is_patroni_master
  become: true

- name: Query test data on worker
  ansible.builtin.shell: psql -U postgres -c "select * from mydata;"
  when: not is_patroni_master
  become: true
